export const degreeList = [
  { label: "B.A.", value: "B.A." },
  { label: "B.S.", value: "B.S." },
  { label: "Coterm", value: "Coterm" },
  { label: "DMA", value: "DMA" },
  { label: "JD", value: "JD" },
  { label: "JSD", value: "JSD" },
  { label: "JSM", value: "JSM" },
  { label: "LLM", value: "LLM" },
  { label: "MA", value: "MA" },
  { label: "MA/JD", value: "MA/JD" },
  { label: "MA/MBA", value: "MA/MBA" },
  { label: "MA/MPP", value: "MA/MPP" },
  { label: "MD", value: "MD" },
  { label: "MFA", value: "MFA" },
  { label: "MLS", value: "MLS" },
  { label: "MPP", value: "MPP" },
  { label: "MS", value: "MS" },
];
